# Generated by Django 4.2.4 on 2023-11-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=12)),
                ('fechaReserva', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad', models.IntegerField()),
                ('correo', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=60)),
                ('observación', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
